// Inlines assets/*.png into src/assets.generated.ts as base64 so the Worker bundle
// (and plain-Node tests) need no binary-module loader.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = new URL("../assets/", import.meta.url).pathname;
const names = readdirSync(dir).filter((f) => f.endsWith(".png")).sort();
const lines = names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(readFileSync(join(dir, n)).toString("base64"))},`);
const out = `// GENERATED by scripts/embed-assets.mjs from assets/*.png — do not edit.
// Regenerate with \`npm run icons\` (macOS; uses CoreGraphics via swift).
export const PASS_IMAGES_BASE64: Record<string, string> = {
${lines.join("\n")}
};
`;
writeFileSync(new URL("../src/assets.generated.ts", import.meta.url), out);
console.log(`embedded ${names.length} images: ${names.join(", ")}`);
